extension:
  - ".purs"

exclude:
  - ".spago/**/*"
  - ".psci_modules/**/*"
  - "generated-docs/**/*"
  - "coverage/**/*"
  - "coverage.js"
  - "dist/**/*"
  - "output/!(Main)/**/*"
  - "output/index.js"

reporter:
  - text
  - html
  - lcov

all: true
