name: ci

on:
  - push

defaults:
  run:
    shell: bash

jobs:
  using-self:
    name: Run hpc-codecov-action
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Building the sample project before running "yarn test", to
      # avoid timeout.
      - name: Build and test sample project with stack
        run: |
          stack --stack-yaml=hs/project1/stack.yaml --skip-msys \
            build --fast --test --coverage

      - name: Build with yarn
        run: yarn && yarn clean && yarn dist

      - name: Run tests
        run: yarn test

      - name: Generate coverage report of project1
        uses: ./
        id: project1
        with:
          build-tool: 'stack'
          build-tool-args: '--skip-msys'
          project-root: 'hs/project1'
          test-suite: 'project1-test'

      - name: Show outputs of project1
        run: |
          echo "outputs.exe: ${{ steps.project1.outputs.exe }}"
          echo "outputs.report: ${{ steps.project1.outputs.report }}"
