name: ci

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'

defaults:
  run:
    shell: bash

jobs:
  run-self:
    name: Build, test, and run self
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Building the sample projects before running "npm test", to
      # avoid timeout.

      - name: Build and test sample project with stack
        run: |
          stack --stack-yaml=hs/project1/stack.yaml --skip-msys \
            build --fast --test --coverage

      - name: Build and test sample project with cabal-install
        run: |
          ( cd hs/project1 && cabal test --enable-coverage )

      - name: Build with npm
        run: npm install && npm run clean && npm run dist

      - name: Run tests with coverage
        run: npm run coverage

      - name: Send coverage report
        run: bash <(curl -s https://codecov.io/bash)

      - name: Generate coverage report of project1 with stack
        uses: ./
        id: p1-stack
        with:
          target: stack:project1-test
          root: hs/project1
          out: p1-stack.json

      - name: Show outputs of p1-stack
        run: |
          echo "outputs.exe: ${{ steps.p1-stack.outputs.exe }}"
          echo "outputs.report: ${{ steps.p1-stack.outputs.report }}"

      - name: Generate coverage report of project1 with cabal
        uses: ./
        id: p1-cabal
        with:
          target: 'cabal:project1-test'
          root: 'hs/project1'
          excludes: 'Main,Paths_project1'
          out: 'p1-cabal.json'

      - name: Show outputs of p1-cabal
        run: |
          echo "outputs.exe: ${{ steps.p1-cabal.outputs.exe }}"
          echo "outputs.report: ${{ steps.p1-cabal.outputs.report }}"
